// apps/api/types/prisma.d.ts
// This file is intentionally empty.
// Prisma types are auto-generated by `prisma generate` and should not be manually declared.
// The generated types are located in node_modules/.prisma/client/index.d.ts
